### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Andyfever123** [zhaozh10/ChatCAD#8]
Your work is impressive and has greatly inspired my research. How can I fine-tune your code using my own dataset, or how can I reproduce your paper from scratch?

**Comment by zhaozh10** [comment]
Our proposed ChatCAD/ChatCAD+ are more like a complicated system than a simple model. Hence, when it comes to fine-tuning, you can only fine-tune the CAD models (e.g. the CAD models mentioned in https://github.com/zhaozh10/ChatCAD/issues/3#issuecomment-1694387328) within the system. For replication purposes, it's more efficient to directly utilize the code snippets from [chat_bot.py](https://github.com/zhaozh10/ChatCAD/blob/main/chat_bot.py) rather than deploying web.py, which launches an interactive web demo.
